[package]
name = "pdf-forensic"
version = "0.1.0"
edition = "2021"
authors = ["kartikpithava"]
description = "A forensic PDF cloning tool with anti-forensic capabilities"
license = "MIT"

[dependencies]
# PDF Processing
lopdf = "0.31.0"
pdf = "0.8.0"

# Cryptography
aes = "0.8.3"
ring = "0.17.5"
sha2 = "0.10.7"
rand = "0.8.5"

# Serialization
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"

# Error Handling
thiserror = "1.0.44"
anyhow = "1.0.72"

# Logging & Monitoring
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

# CLI
clap = { version = "4.3.19", features = ["derive"] }

# Utilities
chrono = "0.4.26"
bytes = "1.4.0"
tempfile = "3.7.0"

[dev-dependencies]
criterion = "0.5.1"
test-case = "3.1.0"
mockall = "0.11.4"
tokio-test = "0.4.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
